#!/usr/bin/python3

# docker-credential-rbw
# Note: the vault needs to be unlocked beforehand because some pinentry binaries requires isatty.

import json
import os
import subprocess
import sys

folderName = (
    os.environ.get("BWHELPER_DOCKER")  # https://github.com/jenbroek/bitwarden-helpers
    or os.environ.get("DOCKER_BITWARDEN_FOLDER")  # https://gitlab.com/eyJhb/docker-credential-bitwarden
    or "docker-creds"  # default of https://github.com/jenbroek/bitwarden-helpers
)


def main(argv):
    if len(argv) == 0:
        print("Usage: docker-credential-rbw <store|get|erase|list|version>")
        return 1
    elif argv[0] == "version":
        print("0.0.1")
        return 0
    elif argv[0] == "erase":
        subprocess.check_output(["rbw", "unlocked"])
        # erase is called for multiple scheme, so it needs to be idempotent ("ensure-erased")
        hostName = sys.stdin.readline().strip()
        subprocess.call(["rbw", "remove", "--folder", folderName, hostName])
        return 0
    elif argv[0] == "store":
        subprocess.check_output(["rbw", "unlocked"])
        data = json.load(sys.stdin)
        if 0 != subprocess.call(["rbw", "get", "--raw", "--folder", folderName, data["ServerURL"]]):
            # call rbw add only if non-existent
            with subprocess.Popen(
                ["rbw", "add", "--folder", folderName, data["ServerURL"], data["Username"]],
                stdin=subprocess.PIPE,
            ) as proc:
                proc.stdin.write(data["Secret"].encode("utf-8"))
                proc.stdin.close()
        return 0
    elif argv[0] == "list":
        subprocess.check_output(["rbw", "unlocked"])
        ret = {}
        for line in (
            subprocess.check_output(["rbw", "search", "--fields", "name,user", "--folder", folderName, ""])
            .decode("utf-8")
            .splitlines()
        ):
            name, user = line.split("\t")
            ret[name] = user
        print(json.dumps(ret, separators=(",", ":"), sort_keys=True))
        return 0
    elif argv[0] == "get":
        subprocess.check_output(["rbw", "unlocked"])
        hostName = sys.stdin.readline().strip()
        try:
            ret = {"ServerURL": hostName, "Username": "", "Secret": ""}
            data = json.loads(subprocess.check_output(["rbw", "get", "--raw", "--folder", folderName, hostName]))
            ret["Username"] = data["data"]["username"]
            ret["Secret"] = data["data"]["password"]
            print(json.dumps(ret, separators=(",", ":")))
        except subprocess.CalledProcessError:
            print("{}")
        return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
